# Database
spring.datasource.url=${JDBC_DATABASE_URL:${DATABASE_URL}}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Hikari settings (avoid timeouts to db causing crashes)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.maximum-pool-size=5


# JPA/Hibernate
#Only using flyway (database-first)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#For saving dates
spring.jackson.serialization.write-dates-as-timestamps=false

#API auth
admin.username=${API_USERNAME}
admin.password=${API_PASSWORD}

#Email settings
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

#For fly.io
server.port=8080
server.address=0.0.0.0